# data path
data_type: "single"
data_root: "jiangxingxun/Data/DFEW/data_affine/single_label/"
work_dir: "./work_dir/mc3_18"
fold_idx: 1

# speed: GPU and memory
gpu_id: 8
num_workers: 1

# hyper-parameter
batch_size: 32
test_gap: "epoch"
optimizer: "Adam"
lr_init: 1e-3

# preprocess: data augment
train_data_augment: False
size_Resize_te: 112

# model: model info, training strategy
model_name: "mc3_18"
model_pretrain: False
model_init: True
